{{ if .Values.config }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: airstore-config-helm
  annotations:
    config-hash: {{ include "sha256sum" (toYaml .Values.config) }}
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
{{- end }}
