apiVersion: v2
name: airstore-chart
description: A Helm chart for Airstore
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/beam-cloud/airstore
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 2.5.0
- name: redis
  version: 18.9.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: 13.4.3
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
